### ISSUE TITLE
Will you provide the trained model?

### ISSUE THREAD

**Issue by YuqingWang1029** [xieenze/PolarMask#1]
Thanks

**Comment by xieenze** [comment]
Yes, please wait for some time.

**Comment by YuqingWang1029** [comment]
> Yes, please wait for some time.

Ok, thanks for your reply.

**Comment by xieenze** [comment]
Hi,
Trained model can be download at here:
https://drive.google.com/drive/folders/1EWtLhWSGuJVtMCS8mTvKNxdYYpz7ufjV?usp=sharing
