### ISSUE TITLE
About remaining bbox branch

### ISSUE THREAD

**Issue by ZhongYingMatrix** [xieenze/PolarMask#10]
Hello, thanks for nice work!
I notice the remaining bbox branch in your fcos instance head, and its loss too. And it's said 'we do not have the bounding box prediction head in PolarMask for simplicity and faster speed' in your paper. 
So I think u may ignore bbox branch in inferencing model, but use its loss back propagation in training model. Have u ever tried to make it bbox-free in both training and inferencing?

**Comment by xieenze** [comment]
Hi,
I did such an experiment and I found the results remain the same for mask mAP.
To simplify, I provide the code for box and mask in code.
You can try to remove box branch or box loss (during training) to verify the mask mAP. 
Thanks.

**Comment by ZhongYingMatrix** [comment]
Thanks for reply~
