### ISSUE TITLE
没太看懂你的polarmask_head.py

### ISSUE THREAD

**Issue by Sillet** [xieenze/PolarMask#13]
hi，尝试了你的代码，几次都没运行成功，所以仔细看了一下的源码，关于PolarMask\mmdet\models\anchor_heads\polarmask_head.py，这部分代码中，line 208，loss函数，我并没有看到你对gt有任何的处理，并且line 225，输出的三个object的维度有时候会是错误的，所以我想了解一下你loss计算中，gt是如何使用的，感谢

我出现的错误：

错误一：

`  File "PolarMask/mmdet/core/bbox/transforms.py", line 215, in distance2bbox
 x1 = points[:, 0] - distance[:, 0]
IndexError: too many indices for tensor of dimension 1`

错误二：
`  File "PolarMask/mmdet/models/losses/mask_iou_loss.py", line 24, in forward
    total = torch.stack([pred, target], -1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 4 and 36 in dimension 1 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71`

基本都是输出维度导致的

**Comment by xieenze** [comment]
Hi
I didn't meet your problems. So do you use COCO dataset? 
I cannot help you if you don't give more details.

**Comment by Sillet** [comment]
I use COCO data
Can you just tell me how you use the gt？because don't see in the loss function how do you use it

**Comment by xieenze** [comment]
@Sillet 
Oh, the loss function is defined in https://github.com/xieenze/PolarMask/blob/master/mmdet/models/losses

And the GT generation is written in https://github.com/xieenze/PolarMask/blob/master/mmdet/datasets/coco_seg.py

**And I use gt and prediction to calculate loss  in** https://github.com/xieenze/PolarMask/blob/master/mmdet/models/anchor_heads/polarmask_head.py
(**line 208-296**).

I think you are not very familiar with MMDetection. You should first learn how to read the code of MMDetection then you will solve these questions by yourself.
Thanks.

**Comment by Sillet** [comment]
thanks

**Comment by XianyuFFF** [comment]
> hi，尝试了你的代码，几次都没运行成功，所以仔细看了一下的源码，关于PolarMask\mmdet\models\anchor_heads\polarmask_head.py，这部分代码中，line 208，loss函数，我并没有看到你对gt有任何的处理，并且line 225，输出的三个object的维度有时候会是错误的，所以我想了解一下你loss计算中，gt是如何使用的，感谢
> 
> 我出现的错误：
> 
> 错误一：
> 
> ` File "PolarMask/mmdet/core/bbox/transforms.py", line 215, in distance2bbox x1 = points[:, 0] - distance[:, 0] IndexError: too many indices for tensor of dimension 1`
> 
> 错误二：
> ` File "PolarMask/mmdet/models/losses/mask_iou_loss.py", line 24, in forward total = torch.stack([pred, target], -1) RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 4 and 36 in dimension 1 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71`
> 
> 基本都是输出维度导致的

请问您是如何解决的?我也是用coco数据集碰到了相同的问题
