### ISSUE TITLE
Cannot import name 'get_dist_info' from mmcv.runner.utils in mmcv 0.2.15 (latest)

### ISSUE THREAD

**Issue by bat3a** [xieenze/PolarMask#16]
hi
i get this error when running the train.py
` File "/home/me/Desktop/PolarMask/mmdet/datasets/loader/sampler.py", line 6, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info'
`
i can train successfully with mmdetection, but not with Polarmask, any help?

**Comment by Flames60** [comment]
mmcv 0.2.10 is OK.

**Comment by bat3a** [comment]
installed 0.2.10 but i get this error:
` File "/home/me/Desktop/deep/PolarMask/mmdet/models/anchor_heads/polarmask_head.py", line 332, in polar_target
    labels_list, bbox_targets_list, mask_targets_list = extra_data.values()
AttributeError: 'NoneType' object has no attribute 'values'
`
i tested 0.2.10 to 0.2.14 the same err.

**Comment by Flames60** [comment]
> installed 0.2.10 but i get this error:
> `File "/home/me/Desktop/deep/PolarMask/mmdet/models/anchor_heads/polarmask_head.py", line 332, in polar_target labels_list, bbox_targets_list, mask_targets_list = extra_data.values() AttributeError: 'NoneType' object has no attribute 'values'`
> i tested 0.2.10 to 0.2.14 the same err.

I think this is another error, and I have run it with 0.2.10 successfully. 
Do you know where is the 'extra_data' forwarded to the loss function? I think this can locate the error, but I am not familiar with the mmdetection.

**Comment by Flames60** [comment]
you can check the forward_train func in 
`./mmdet/models/detectors/polarmask.py`

**Comment by bat3a** [comment]
extra_data in polarmask_head.py is empty:
`labels_list, bbox_targets_list, mask_targets_list = extra_data.values()`
why is that, anyway to solve this.

**Comment by bat3a** [comment]
it there away to update mmdet inside this repository?! please help
i can successfully use mmdetection models but not Polarmask

**Comment by Hanawh** [comment]
> it there away to update mmdet inside this repository?! please help
> i can successfully use mmdetection models but not Polarmask

change /PolarMask/mmdet/datasets/loader/sampler.py line 6 `from mmcv.runner.utils import get_dist_info`to `from mmcv.runner import get_dist_info`
