### ISSUE TITLE
What is the target and input of the centerness loss?

### ISSUE THREAD

**Issue by Flames60** [xieenze/PolarMask#17]
```
287                 loss_centerness = self.loss_centerness(pos_centerness,
288                                                        pos_centerness_targets)
```
I found it is a 1-d tensor, so what is the meaning of this? I think it is not the center map.

**Comment by xieenze** [comment]
The w,h are flatten to 1d....

**Comment by xieenze** [comment]
Sorry I can not reply timely because I do not sign in github several days.
Anyway, In this question, why the centerness is 1d, because the 'w' and 'h' are flatten into 1d. Like the cls and mask branch.
