### ISSUE TITLE
模型文件'../work_dirs/debug/MASK_BRANCH/mask_center_v1.100/epoch_14.pth'

### ISSUE THREAD

**Issue by pioneer158** [xieenze/PolarMask#22]
你好，有训练好的模型文件吗？

**Comment by zack624** [comment]
Readme的[google driver](https://drive.google.com/drive/folders/1EWtLhWSGuJVtMCS8mTvKNxdYYpz7ufjV?usp=sharing)

**Comment by pioneer158** [comment]
thank you！
