### ISSUE TITLE
test error: UnboundLocalError: local variable '_mlvl_bboxes' referenced before assignment

### ISSUE THREAD

**Issue by zack624** [xieenze/PolarMask#23]
when I executed `python tools/test.py configs/polarmask/4gpu/polar_768_1x_r50.py /root/coco/r50_1x.pth --show`, I got the error as title. And I am confused in the polarmask_head.py.
`         
def get_bboxes_single

        mlvl_bboxes = torch.cat(mlvl_bboxes)
        mlvl_masks = torch.cat(mlvl_masks)
        if rescale:
            _mlvl_bboxes = mlvl_bboxes / mlvl_bboxes.new_tensor(scale_factor)
            try:
                scale_factor = torch.Tensor(scale_factor)[:2].cuda().unsqueeze(1).repeat(1, 36)
                _mlvl_masks = mlvl_masks / scale_factor
            except:
                _mlvl_masks = mlvl_masks / mlvl_masks.new_tensor(scale_factor)
        mlvl_scores = torch.cat(mlvl_scores)
        padding = mlvl_scores.new_zeros(mlvl_scores.shape[0], 1)
        mlvl_scores = torch.cat([padding, mlvl_scores], dim=1)
        mlvl_centerness = torch.cat(mlvl_centerness)
        centerness_factor = 0.5  # mask centerness is smaller than origin centerness, so add a constant is important or the score will be too low.
        if self.mask_nms:
            '''1 mask->min_bbox->nms, performance same to origin box'''
            a = _mlvl_masks
            _mlvl_bboxes = torch.stack([a[:, 0].min(1)[0],a[:, 1].min(1)[0],a[:, 0].max(1)[0],a[:, 1].max(1)[0]],-1)
            det_bboxes, det_labels, det_masks = multiclass_nms_with_mask(
                _mlvl_bboxes,
                mlvl_scores,
                _mlvl_masks,
                cfg.score_thr,
                cfg.nms,
                cfg.max_per_img,
                score_factors=mlvl_centerness + centerness_factor)

        else:
            '''2 origin bbox->nms, performance same to mask->min_bbox'''
            det_bboxes, det_labels, det_masks = multiclass_nms_with_mask(
                _mlvl_bboxes,
                mlvl_scores,
                _mlvl_masks,
                cfg.score_thr,
                cfg.nms,
                cfg.max_per_img,
                score_factors=mlvl_centerness + centerness_factor)

        return det_bboxes, det_labels, det_masks`

In the function get_bboxes_single, the variables _mlvl_bboxes and _mlvl_masks are both used after if self.mask_nms, but if rescale is False, the _mlvl_bboxes and _mlvl_masks is not assignmented, so I got the error. 
Then I set the rescale always True, but I got another error by `img_show[mask] = img_show[mask] * 0.5 + color_mask * 0.5` in base.py
 IndexError: boolean index did not match indexed array along dimension 0; dimension is 768 but corresponding boolean dimension is 427

**Comment by zack624** [comment]
And I also tried to change all the variables `_mlvl_*` to `mlvl_*` (just as anchor_head.py), but I still got the same IndexError.

**Comment by zack624** [comment]
I have solved it by:
1. in function get_bboxes_single of polarmask_head.py, added 
`
    _mlvl_bboxes = mlvl_bboxes;
    _mlvl_masks = mlvl_masks
`
before `if rescale:`
2. in function show_result of base.py, changed 
`h, w, _ = img_meta['img_shape']` to `h, w, _ = img_meta['ori_shape']`

**Comment by helq2612** [comment]
https://github.com/xieenze/PolarMask/issues/23#issuecomment-599014948 does not work for me. It still outputs that error. In the second step, I modified it as below, and it works for me:
2. in function show_result of base.py, changed
```
  h, w, _ = img_meta['img_shape']
  img_show = img[:h, :w, :]
  ori_h, ori_w = img_meta['ori_shape'][:-1]
  img_show = mmcv.imresize(img_show, (ori_w, ori_h))
```
