### ISSUE TITLE
关于Polar IoU的问题

### ISSUE THREAD

**Issue by Dawn-LX** [xieenze/PolarMask#25]
您好，我对于您论文中的Polar IoU有些疑问
（1） 公式 (6) 中的 d_{min} = min(d,d*)  应该是指 min(d_i, d*_i)吧？ 就是说在累加的时候，应该是遍历d_i 和d*_i的吧？
（2）把公式(6)换成公式(7)会提升一些性能，但这样似乎失去了IoU本身的含义，感觉有点玄学

希望能解答一下，谢谢！

**Comment by xieenze** [comment]
Hi
for (1) yes, we will use i from 1 to 36.
for (2), formula(6)and (7) are nearly equal,  also the performance is very close. We remove the ^2 only for simplify.

**Comment by Dawn-LX** [comment]
> Hi
> for (1) yes, we will use i from 1 to 36.
> for (2), formula(6)and (7) are nearly equal, also the performance is very close. We remove the ^2 only for simplify.

Thank you very much ！！
