### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by jiafucan** [xieenze/PolarMask#27]
您好，我在训练的时候遇到了extra_data值为空的问题，我打印出‘_gt_masks’，‘_gt_labels’，‘_gt_bboxes’发现全部都是None，我想为什么会出现这样的问题？感谢回复。
`    labels_list, bbox_targets_list, mask_targets_list = extra_data.values()
AttributeError: 'NoneType' object has no attribute 'values'`

**Comment by sporterman** [comment]
@jiafucan 请问这个问题解决了吗
