### ISSUE TITLE
Acc/speed trade-off

### ISSUE THREAD

**Issue by zzzzzz0407** [xieenze/PolarMask#3]
Hi, I would like to know if the acc/speed trade-off on ResNet-50, i.e., scale-400/600/800, just simply trained with 800 then using different scale  during inference, or just train multi models, respectively?

**Comment by xieenze** [comment]
simply trained with 800 then using different scale during inference

**Comment by xieenze** [comment]
if  training  with different scales, i think  the performance will be improved. 
but it is not important in the paper, so we simply test it in different scales.

**Comment by zzzzzz0407** [comment]
Thank you, it's a wonderful work!
