### ISSUE TITLE
KeyError: 'PolarMask is not in the detector registry'

### ISSUE THREAD

**Issue by LittleQQ** [xieenze/PolarMask#32]
@xieenze when i run train.py,it appear KeyError: 'PolarMask is not in the detector registry', i do'nt know how to solve the problem,i expect your helpness

**Comment by DoUntilFalse** [comment]
Maybe [issue #11]( https://github.com/xieenze/PolarMask/issues/11#issuecomment-558443087) will be helpful for you.
I also encountered this problem a few days ago, and I think maybe you should execute `python setup.py develop` in PolarMask but not in mmdetection.
Hope my answer can help you.

**Comment by xieenze** [comment]
> Maybe [issue #11](https://github.com/xieenze/PolarMask/issues/11#issuecomment-558443087) will be helpful for you.
> I also encountered this problem a few days ago, and I think maybe you should execute `python setup.py develop` in PolarMask but not in mmdetection.
> Hope my answer can help you.

yes, you should install PolarMask not MMdetection
