### ISSUE TITLE
关于groud_truth

### ISSUE THREAD

**Issue by jiaxinshiwo** [xieenze/PolarMask#33]
我想问一下在计算loss的时候，
labels, bbox_targets, mask_targets = self.polar_target(all_level_points, extra_data)
这里的extra_data是怎么计算的

**Comment by xieenze** [comment]
Hi
the extra data is the ground-truth, which is calculated in this file.
![image](https://user-images.githubusercontent.com/20984575/81462516-8ac62080-91e5-11ea-9e88-4a71d8a9e205.png)
