### ISSUE TITLE
About the bbox loss

### ISSUE THREAD

**Issue by rika1024** [xieenze/PolarMask#34]
I see there are totally 4 lossese in your code, (centerness, cls, mask, and bbox). The bbox loss is not mentioned in the paper, is the same loss with FCOS?

**Comment by xieenze** [comment]
Yes, I have mentioned in the ablation study to show with/without box loss. 
The box loss is the same as the FCOS box branch. You can easily remove it.
If you disable box loss, the NMS is performed on the mask.

**Comment by rika1024** [comment]
Thanks for your reply
