### ISSUE TITLE
what's the difference between get_centerpoint and x,y=count.mean(axis=0)? and why?

### ISSUE THREAD

**Issue by Dawn-LX** [xieenze/PolarMask#36]
Problem about compute _gt_masks at get_centerpoint in 
https://github.com/xieenze/PolarMask/blob/90c479856fa8aa1e2d519886df5a5f8a58a4aaf2/mmdet/datasets/coco_seg.py#L522

what's the difference between get_centerpoint and x,y=count.mean(axis=0)? and why?
Can you please explain this to me？, thank you!!

**Comment by Dawn-LX** [comment]
`try:
            center = self.get_centerpoint(count)
        except:
            x,y = count.mean(axis=0)
            center=[int(x), int(y)]`

**Comment by xieenze** [comment]
Hi
Great question.
I think they are almost the same. 
**self.get_centerpoint(count)** is to calculate the mass center based on the **mask**, but when the input mask is small it will face some bugs, I did not fix it.
So I use {try,catch} to handle the bug, **x,y = count.mean(axis=0) center=[int(x), int(y)]**, This is to calculate the mass center based on the **contour**.

The results of these two ways to are almost the same. If you have other question, please let me know, thanks.

**Comment by Dawn-LX** [comment]
Thank you very much
