### ISSUE TITLE
是否使用了GN？

### ISSUE THREAD

**Issue by wanghaijie2017** [xieenze/PolarMask#4]
``` python
# model settings
model = dict(
    type='FCOS',
    pretrained='open-mmlab://resnet50_caffe',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=False),
        style='caffe'),
```
在readme中使用了GN，但配置文件里norm_cfg类型用的是BN。

**Comment by xieenze** [comment]
Hi,
GN is used in the head of the network, same as FCOS.
Here BN is used in the backbone. It is a common setting.

**Comment by wanghaijie2017** [comment]
> Hi,
> GN is used in the head of the network, same as FCOS.
> Here BN is used in the backbone. It is a common setting.

Thanks for your quick reply, your work is very novel.
