### ISSUE TITLE
About Equations (1, 2) in the paper and the implemented distance2mask function

### ISSUE THREAD

**Issue by andgitchang** [xieenze/PolarMask#40]
Hi,
Are the (x, y) in [distance2mask](https://github.com/xieenze/PolarMask/blob/90c479856fa8aa1e2d519886df5a5f8a58a4aaf2/mmdet/models/anchor_heads/polarmask_head.py#L492) equivalent to the (x, y) shown in Equation (1) and (2) of the paper? Since sin/cos operate on the opposites (x, y), if i understand correctly. Thanks.
`x = distances * sin + c_x`
`y = distances * cos + c_y`

**Comment by tikboaHIT** [comment]
Have you solved this problem?
I have the same confusion
