### ISSUE TITLE
'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by sporterman** [xieenze/PolarMask#42]
labels_list, bbox_targets_list, mask_targets_list = extra_data.values() 
how to solve this? @xieenze  #16 can't solve this.

**Comment by zhangyingbit** [comment]
It seems you use wrong "dataset_type" in the config file. It should be "Coco_Seg_Dataset" or "Coco_SegFast_Dataset" for PolarMask because PolarMask needs to convert the coco format to the format what it needs. And please make sure the file "coco_seg.py" or "coco_seg_fast.py" in the path "PolarMask/mmdet/datasets". Hope it can help you : )

**Comment by sporterman** [comment]
@zhangyingbit i use custom dataset as follow:
![image](https://user-images.githubusercontent.com/13059352/86108732-1ed1ab80-baf6-11ea-8c16-91fe6823d95e.png)

so in config file, 'dataset_type = custom_dataset_name',   should dataset_type must in one of ["Coco_Seg_Dataset", "Coco_SegFast_Dataset"]

**Comment by zhangyingbit** [comment]
@sporterman Yes, you are right~

**Comment by sporterman** [comment]
but i got that error, set 'dataset_type = Coco_Seg_Dataset' ?

**Comment by sporterman** [comment]
@zhangyingbit  thanks, i know how to solve that, that code need coco_seg.py, not coco.py,  so i shoud make custom_dataset_seg.py

**Comment by zhangyingbit** [comment]
@sporterman can you send the error information to my email(zhangyingbit@163.com), I can't see the image you upload here.

**Comment by zhangyingbit** [comment]
@sporterman Yes, the custom.py PolarMask use maybe different from the version in your mmdet, you can copy PolarMask/mmdet/datasets/custom.py and rename it custom_dataset_seg.py, also change class name and the init.py, good luck for you : )
