### ISSUE TITLE
Hello friends, how to train with my own coco format datasets, please provide the step by step guide? will be helpful?

### ISSUE THREAD

**Issue by RabiSharma-1987** [xieenze/PolarMask#43]

**Comment by xieenze** [comment]
Hello,
You can find the tutorial in mmdetection, 
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_dataset.md

In briefly you only need to generate a json file, containing the img and label. Then you can change the config to use your dataset.
