### ISSUE TITLE
请问代码实现的方法有变化吗

### ISSUE THREAD

**Issue by Dominix-411** [xieenze/PolarMask#47]
因为我发现mmdetection里面好像没有PolarMask的代码，请问大佬有没有可能对应着更改下实现的readme

**Comment by xieenze** [comment]
额，我暂时没时间往新版的mmdet里合并我的代码，如果你有兴趣可以帮忙搞一下，感谢

**Comment by xlim1997** [comment]
@Dominix-411  请问您实现了基于新版本的mmdetection的polarmask了吗

**Comment by luoshuifeiyang** [comment]
> @Dominix-411 请问您实现了基于新版本的mmdetection的polarmask了吗

请问您最后是怎么解决的这个问题？
