### ISSUE TITLE
Polygon3 import error

### ISSUE THREAD

**Issue by YuqingWang1029** [xieenze/PolarMask#5]
I installed the Polygon3 module using pip, but when i import Polygon, it says 

from Polygon.cPolygon import *
ImportError: /home/...open-mmlab/lib/python3.7/site-packages/Polygon/cPolygon.cpython-37m-x86_64-linux-gnu.so: undefined symbol: alloca

Have you met the same problem?

**Comment by xieenze** [comment]
No, I didn't meet this problem.

**Comment by YuqingWang1029** [comment]
> No, I didn't meet this problem.

Ok, i tried another machine and solved the problem.
