### ISSUE TITLE
How does number of Rays affects FPS

### ISSUE THREAD

**Issue by luoyixin2019** [xieenze/PolarMask#51]
Hi Enze!
I saw you have do experiment about **number of Rays** in you paper(Table1 a). It illustrate that more rays product higher AP. So what about FPS? Have you ever do such experiment that how does number of Rays affects FPS?

It seems that the FPS should be lower when we use more ray for mask representation, but in my experiment(some other dataset), the result is reversed! I got higher AP and lower FPS when I use less rays for mask.

I hope for your reply!

**Comment by xieenze** [comment]
The FPS has little influence on FPS. Because it only increases the channel of the output feature for the mask branch.

**Comment by luoyixin2019** [comment]
Thanks for your apply.
