### ISSUE TITLE
模型无法收敛

### ISSUE THREAD

**Issue by qq3266452048** [xieenze/PolarMask#53]
我试着在total text训练，但是模型始终无法收敛。map始终在10左右。
相比之下在icdar15上则很快收敛。准确率也很高。如果大佬能给点建议就好了。

**Comment by qq3266452048** [comment]
过了几天还是发现能收敛，想问下大佬，有没有在total text或者ctw1500上跑过。结果能到多少？

**Comment by FantDing** [comment]
> 过了几天还是发现能收敛，想问下大佬，有没有在total text或者ctw1500上跑过。结果能到多少？

是相比与其他模型收敛慢吗，我也是没法收敛，加载这个仓库提供的训练模型可以。

**Comment by qq3266452048** [comment]
> > 过了几天还是发现能收敛，想问下大佬，有没有在total text或者ctw1500上跑过。结果能到多少？
> 
> 是相比与其他模型收敛慢吗，我也是没法收敛，加载这个仓库提供的训练模型可以。

在ctw和total上确实效果不是很好，但还是勉强可以跑的

**Comment by SSZ1** [comment]
请问你做精度评定的时候，报过这个错误吗？

(testpy37) root@interactive85669:/opt/data/private/SSZ/test/PolarMask/PolarMask# python tools/test.py configs/polarmask/4gpu/polar_768_1x_r50.py /opt/data/private/SSZ/test/PolarMask/result/20220516complete/60epoch/epoch_60.pth --out /opt/data/private/SSZ/test/PolarMask/result/20220516complete/60epoch/results.pkl --eval segm
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
/opt/data/private/SSZ/test/PolarMask/PolarMask/mmdet/models/anchor_heads/polarmask_head.py:72: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  self.angles = torch.range(0, 350, 10).cuda() / 180 * math.pi
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 60/60, 0.3 task/s, elapsed: 172s, ETA:     0s
writing results to /opt/data/private/SSZ/test/PolarMask/result/20220516complete/60epoch/results.pkl
Starting evaluate segm
Traceback (most recent call last):
  File "tools/test.py", line 225, in <module>
    main()
  File "tools/test.py", line 201, in main
    result_files = results2json(dataset, outputs, args.out)
  File "/opt/data/private/SSZ/test/PolarMask/PolarMask/mmdet/core/evaluation/coco_utils.py", line 165, in results2json
    json_results = segm2json(dataset, results)
  File "/opt/data/private/SSZ/test/PolarMask/PolarMask/mmdet/core/evaluation/coco_utils.py", line 135, in segm2json
    data['category_id'] = dataset.cat_ids[label]
IndexError: list index out of range

**Comment by SSZ1** [comment]
IndexError：list index of range
