### ISSUE TITLE
about debug IndexError: list index out of range

### ISSUE THREAD

**Issue by pandamax** [xieenze/PolarMask#7]
Thanks for your contribution.

yep,you have mentioned that `debug IndexError: list index out of range' in `coco_seg.py`

 I try to use your model `polar_768_1x_r50_4gpu` to train coco-style datasets.At first,it can be trained using the coco-style dataset,and then a error occured as shown below.Before fix the bug,I want to determine if the problem is caused by the dataset format itself or by the dataset conversion.

```
2019-10-18 09:20:17,323 - INFO - Epoch [1][180/320]	lr: 0.00572, eta: 2:48:15, time: 1.506, data_time: 0.044, memory: 6851, loss_cls: 0.1853, loss_bbox: 0.6263, loss_mask: 0.3083, loss_centerness: 0.5536, loss: 1.6735
2019-10-18 09:20:46,074 - INFO - Epoch [1][190/320]	lr: 0.00585, eta: 2:48:10, time: 2.875, data_time: 0.139, memory: 6851, loss_cls: 0.1767, loss_bbox: 0.6881, loss_mask: 0.3242, loss_centerness: 0.5494, loss: 1.7385

IndexError: Caught IndexError in DataLoader worker process 1.
 count = contour[0][:, 0, :]
IndexError: list index out of range
```
thanks for your help inadvance.

**Comment by xieenze** [comment]
Hi,
I don't know why you have this error. Have you changed the input image size?

At first, I have meet this error because there are some very small instances, and their mask labels are none. But when I add some filter rules in coco_seg.py(line 127), then this error disappears. 

Maybe you can try to further filter masks with more strict rules. But I think under the size of 768, this error shouldn't occur.

**Comment by xieenze** [comment]
Hi, I notice that you may not use coco dataset because the iter=320 in 1 epoch.
If you use other datasets, you need to pay attention on the problems I mentioned above. Filter the tiny instance with none label is important.

**Comment by pandamax** [comment]
> Hi, I notice that you may not use coco dataset because the iter=320 in 1 epoch.
> If you use other datasets, you need to pay attention on the problems I mentioned above. Filter the tiny instance with none label is important.

thanks for your suggestion,i will continue to troubleshoot bugs based on the my coco-style datasets.
thanks again~
