### ISSUE TITLE
Is there any demo for visualization?

### ISSUE THREAD

**Issue by zzzzzz0407** [xieenze/PolarMask#8]
Hi, thanks for your wonderful work, but I do not find a demo to test the image and then visualize it, can you share one?

**Comment by xieenze** [comment]
Sorry, I do not have enough time to do these things before 2019.11.20. 
I will consider adding these tools and demo.

**Comment by zzzzzz0407** [comment]
Okay, thanks anyway, I will try it myself.

**Comment by pandamax** [comment]
> Okay, thanks anyway, I will try it myself.
hi,do you have any idea to visualize the tested image?

**Comment by pandamax** [comment]
> Okay, thanks anyway, I will try it myself.

hi,do you have any idea to visualize the tested image?

**Comment by zzzzzz0407** [comment]
@pandamax PolarMask is just based on mmdetection, just follow the demo https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb
it is quite easy.

**Comment by xieenze** [comment]
> @pandamax PolarMask is just based on mmdetection, just follow the demo https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb
> it is quite easy.

Thanks. I ignore this tool. Have you successfully use this tool to visualize the images during inference?

**Comment by pandamax** [comment]
@zzzzzz0407 @xieenze thanks a lot，I am not familiar with this tool. I use PolarMask to train my own coco-style datasets. emmmm,I just look at the demo,it  seems to only show the detection box，and I want to show the segmentation result as well. Maybe this tool contains this feature, but I didn't find it.

thanks a lot again.

**Comment by zzzzzz0407** [comment]
@xieenze 
yeal, it is easy, but PolarMask is not perfectly compatible with mmdetection, so you may modify some detail firstly.
I find that PolarMask has no **cfg.data.test.size_divisor** in its config_file, yet the default inference needs this, so I just set **it=None**, like this:
`
In mmdet/api/inference/inference_detector, about line 63

img_transform = ImageTransform(
        **size_divisor=None**, **cfg.img_norm_cfg)
`

**Please check it, I cannot ensure its influence to other function.**

Then just follow the demo, put the demo at tools/
`
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv

config_file = '../configs/polarmask/4gpu/polar_768_1x_r50.py'
checkpoint_file = '../checkpoints/r50_1x.pth
model = init_detector(config_file, checkpoint_file, device='cuda:0')

img = './000000465179.jpg'
result = inference_detector(model, img)
show_result_pyplot(img, result, model.CLASSES)
`

**Comment by xieenze** [comment]
@zzzzzz0407 @pandamax 
Thanks for your advice. I try to visualize polarmask. You need to set 'size_divisor=32' in the config file and do not need to change the code in inference.py.
Details are shown below.
![image](https://user-images.githubusercontent.com/20984575/67615848-bc583b00-f803-11e9-9a19-781e14b69655.png)

And I also upload a file in ./demo folder.
Thanks for your advice!

**Comment by PinxueGuo** [comment]
I'm willing to share  a simple code which is simple for visualization.

```
from mmdet.apis import init_detector, inference_detector, show_result_pyplot, show_result
import mmcv
import os
import cv2

config_file = '/home/gpx/PolarMask/configs/polarmask/4gpu/polar_768_1x_x101.py'
checkpoint_file = '/home/gpx/PolarMask/x101_1x.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')

img_path = '/home/gpx/PolarMask/test_img'
output_path = '/home/gpx/PolarMask/test_img_result/X-101_128'
img_names = os.listdir(img_path)
for name in img_names:
    img = os.path.join(img_path, name)
    result = inference_detector(model, img)
    img_result = show_result(img, result, model.CLASSES, score_thr=0.3, show=False)
    save_path = os.path.join(output_path, f'{name}_result.jpg')
    cv2.imwrite(save_path, img_result)
    print(name+' DONE!')
```
