### ISSUE TITLE
Some questions about the speed.

### ISSUE THREAD

**Issue by zzzzzz0407** [xieenze/PolarMask#9]
I have tested the ResNet-50 with one GTX TITANX, however, 
with(1280, 768) --> FPS =5,
with(667, 400) --> FPS = 7,
Firstly, it is far slower than the paper's speed (8.9&19.0, respectively);
Secondly, why the speeds of different scales is so near, 400 shares only 1/4 computation compared with 800 in model, is that means the post-process is time-consuming？

**Comment by zzzzzz0407** [comment]
Moreover, I find that in code you still output the box branch, rather than the mask assembing for fast nms as introduced in your paper.

**Comment by xieenze** [comment]
hi
1 The speed now only contains model inference. It is metioned in our paper. We will update the whole speed in the later version of paper.
2 with/without box branch have tiny difference in final results. It is also metioned in the paper. 
If you remove the box branch during training/testing , the results is almost the same.
You can check the code in fcos_instance_head_miou_mskctness.py (line 474 and line 486) to find the two nms methods(box nms and mask－>box nms.).

**Comment by xieenze** [comment]
3. In the latest version, I have pushed some code to optimize the post-processing speed. (see 'distance2mask' function in fcos_instance_head_miou_mskctness.py). Please notice that.
And I test the speed is 12 fps with R101 (include post-process) on single V100 GPU.
These information will be updated in the new version of paper.

**Comment by zzzzzz0407** [comment]
Okay, thanks for your reply.
